# Generated by Django 5.2.1 on 2025-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chate_eris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gecmis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gecmis_islemler', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='giris_mesaji',
            name='slug',
            field=models.SlugField(blank=True, max_length=155, null=True, unique=True),
        ),
    ]
